# ansible-playbook ansible/pb_api_reload.yml

- hosts: local
  remote_user: root


  vars:
    git_project_path: "{{deploy_project_path}}/{{git_repository_name}}"
  vars_files:
    - vars/local.yml


  tasks:
    - include: task/service_reload.yml

  handlers:
     - name: handler_run_uwsgi
       command: uwsgi ./../conf/{{uwsgi_file}}