# ansible-playbook ansible/pb_ec2.yml

- hosts: aws_ec2
  become_user: root
  gather_facts: false

  vars:
    ansible_ssh_private_key_file: /Volumes/Mac-TBD/Server/aws-ec2/sing-ub-py.pem
    git_project_path: /home/ubuntu/api36/server-api-py
    uwsgi_port: 88

  tasks:
    - name: Check git file list
      shell: chdir={{git_project_path}} ls -a
      register: git_ls

    - name: Display file list from git
      debug: msg="{{ git_ls.stdout_lines }}"
      when: git_ls|success

    - name: Git pull
      shell: chdir={{git_project_path}} git pull
      sudo: yes
      register: git_pull

    - name: Display latest file list from git
      debug: msg="{{ git_pull.stdout_lines }}"
      when: git_pull|success

    - name: Project python package changed? need pip install...!
      shell: chdir={{git_project_path}} cat requirements.txt
      when: git_pull.stdout.find('requirements') >= 0
      notify:
        - handler_pip_install
      register: requirements_txt
      ignore_errors: True

    - name:  Display python package if changed!
      debug: msg="{{ requirements_txt.stdout_lines }}"
      when:  git_pull.stdout.find('requirements') >= 0

    - name:  Project file changed? need restart server!
      debug: msg="{{git_pull.stdout}}"
      when: git_pull.stdout.find('Already up-to-date') < 0
      notify:
        - handler_restart_api
      ignore_errors: True

    - name: pip3
      shell: pip3 -V
      register: pip3_python

    - debug: msg="{{ pip3_python.stdout_lines }}"


  handlers:
     - name: handler_pip_install
       shell: chdir={{git_project_path}} fab install
       sudo: yes

     - name: handler_restart_api
       shell: pip3 -V




