# ansible-playbook ansible/pb_ec2.yml

- hosts: aws_ec2
  become_user: root
  gather_facts: false

  vars:
    ansible_ssh_private_key_file: /Volumes/Mac-TBD/Server/aws-ec2/sing-ub-py.pem
    git_project_path: /home/ubuntu/api36/server-api-py
    uwsgi_port: 88

  tasks:
    - name: Check git file list
      shell: chdir={{git_project_path}} ls -a
      register: git_ls

    - name: Display file list from git
      debug: msg="{{ git_ls.stdout_lines }}"
      when: git_ls|success

    - name: Git pull
      shell: chdir={{git_project_path}} git pull
      sudo: yes
      register: git_pull

    - name: Display latest file list from git
      debug: msg="{{ git_pull.stdout_lines }}"
      when: git_pull|success


    - debug: msg="item.item={{item}}"
      when: "{{item.find('requirements') >= 0}}"
      ignore_errors: True
      with_items: "{{git_ls.stdout_lines}}"


    - name: pip3
      shell: pip3 -V
      register: pip3_python

    - debug: msg="{{ pip3_python.stdout_lines }}"

