# ansible-playbook ansible/pb_ec2.yml

- hosts: aws_ec2
  become_user: root
  gather_facts: false

  vars:
    ansible_ssh_private_key_file: /Volumes/Mac-TBD/Server/aws-ec2/sing-ub-py.pem
    git_project_path: /home/ubuntu/api36/server-api-py
    uwsgi_port: 88

  tasks:
    - name: Check git file list
      shell: chdir={{git_project_path}} ls -a
      register: git_ls

    - name: Display file list from git
      debug: msg="{{ git_ls.stdout_lines }}"
      when: git_ls|success

    - name: Git pull
      shell: chdir={{git_project_path}} git pull
      sudo: yes
      register: git_pull

    - name: Display latest file list from git
      debug: msg="{{ git_pull.stdout_lines }}"
      when: git_pull|success

    - name: Whether need re-install python package?
      shell: chdir={{git_project_path}} cat requirements.txt
      when: git_pull.stdout.find('requirements') >= 0
      register: requirements_txt

    - name:  Display requirements file
      debug: msg="{{requirements_txt.stdout_lines}}, pip install..."
      when:  git_pull.stdout.find('requirements') >= 0
      notify:
        - handler pip install
      ignore_errors: True

    - debug: msg="item.item={{git_pull.stdout}}, do nothing"
      when: git_pull.stdout.find('Already up-to-date') >= 0
      ignore_errors: True

    - name: pip3
      shell: pip3 -V
      register: pip3_python

    - debug: msg="{{ pip3_python.stdout_lines }}"


  handlers:
     - name: handler pip install
       shell: pip3 -V




